apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    name: traefik-ingress-controller
    namespace: kube-system
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    annotations:
      deprecated.daemonset.template.generation: "0"
    creationTimestamp: null
    labels:
      k8s-app: traefik-ingress-lb
    name: traefik-ingress-controller
    namespace: kube-system
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    template:
      metadata:
        creationTimestamp: null
        labels:
          k8s-app: traefik-ingress-lb
          name: traefik-ingress-lb
      spec:
        containers:
        - args:
          - --api
          - --kubernetes
          - --logLevel=INFO
          image: traefik:v1.7
          imagePullPolicy: IfNotPresent
          name: traefik-ingress-lb
          ports:
          - containerPort: 80
            hostPort: 80
            name: http
            protocol: TCP
          - containerPort: 8080
            hostPort: 8080
            name: admin
            protocol: TCP
          resources: {}
          securityContext:
            capabilities:
              add:
              - NET_BIND_SERVICE
              drop:
              - ALL
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: traefik-ingress-controller
        serviceAccountName: traefik-ingress-controller
        terminationGracePeriodSeconds: 60
    updateStrategy:
      type: OnDelete
  status:
    currentNumberScheduled: 0
    desiredNumberScheduled: 0
    numberMisscheduled: 0
    numberReady: 0
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: traefik-ingress-service
    namespace: kube-system
  spec:
    ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
    - name: admin
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      k8s-app: traefik-ingress-lb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
